plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.11'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'co.kr.mmsoft'
version = '0.0.1-SNAPSHOT'
description = 'mm-config-server'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}


configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

ext {
    set('springCloudVersion', "2025.0.1")
}
dependencies {
    // 1. Config Server 핵심
    implementation 'org.springframework.cloud:spring-cloud-config-server'

    // 2. 웹 환경 (에러 원인이었던 WebMvcAutoConfiguration 해결용)
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // 3. 모니터링 및 설정 갱신용
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    /*
MSA 환경에서 Eureka, K8s(쿠버네틱스)의 경우 Config Server가 살아있는지 주기적으로 호가인함,
이때 actuator가 필요함
 */
    // 프로메테우스에게 매트릭(Metrics- 수치화된 데이터) 제공하기
    implementation("io.micrometer:micrometer-registry-prometheus")

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.14.3'

// 실제 코드용 Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

// 테스트 코드에서 Lombok(@Slf4j 등)을 사용하기 위해 반드시 필요!
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}


test {
    useJUnitPlatform()

    testLogging {
        // 테스트 실행 시 로그 이벤트 설정
        events "passed", "skipped", "failed", "standardOut", "standardError"

        // 상세 로그 출력 여부
        showStandardStreams = true
    }

}
tasks.named('test') {
    useJUnitPlatform()
}
