#----------------------------------------------
# Github의 Config Repo에 올려 놓으면 안되는 이유?
# Config Repo는 모든 애플리케이션에 저굥ㅇ되는 공통 소스이므로 충돌남
# 해결책) config server의 로컬에서 관리해야함
#----------------------------------------------
server:
  port: 1881

spring:
  application:
    name: mm-config-server

  #----------------------------------------------
  # msa를 이루는 모든 구성 서버들에게 config repo의 yml파일 정보를 읽어 제공하려면
  # config 서버는 github 접속할 능력이 있어야 함
  #----------------------------------------------
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ideammsoft/mm-repo.git
          default-label: main
          username: ideammsoft
          password: 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

          clone-on-start: true #서버 가동시 즉각 git clone 수행
          force-full: true

#shop-config-server 자체 로그 출력
logging:
  level:
    root: info
    com.ch.shopconfigserver: debug